### ISSUE TITLE
Lambda function environment variables

### ISSUE THREAD

**Issue by LuigiClemente-Awin** [cloudposse/terraform-aws-datadog-lambda-forwarder#12]
Hi all

I do not understand how to add a new environment variable for the Lambda forwarder configuration.
In my case, for example, I need to set DD_SITE as we use the european datadog endpoint.

Thanks,

Luigi

**Comment by jamengual** [comment]
You can't right now : 

```  lambda_debug           = var.forwarder_lambda_debug_enabled ? { DD_LOG_LEVEL = "debug" } : {}
  lambda_env             = merge(local.dd_api_key_kms, local.dd_api_key_asm, local.dd_api_key_ssm, local.lambda_debug)```

But you could create a PR to add something like : 

```
  lambda_debug           = var.forwarder_lambda_debug_enabled ? { DD_LOG_LEVEL = "debug" } : {}
  lambda_env             = merge(local.dd_api_key_kms, local.dd_api_key_asm, local.dd_api_key_ssm, local.lambda_debug, var.custom_environment_variables)
```

**Comment by jamengual** [comment]
you will need to make sure the new input variable is formated correctly etc, it will be a map with key and values.
