### ISSUE TITLE
hashicorp/template deprecated, unable to use this package on darwin-arm64

### ISSUE THREAD

**Issue by bberzinskas-tw** [cloudposse/terraform-aws-datadog-lambda-forwarder#34]
Found a bug? Maybe our [Slack Community](https://slack.cloudposse.com) can help. 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Bug
Checked out a working project that uses this module on new M1 machine.   run `terraform init` and receive
```
Error: Incompatible provider version

Provider registry.terraform.io/hashicorp/template v2.2.0 does not have a package available for your current platform, darwin_arm64.
```

According to `hashicorp/templates`, the provider was deprecated before M1 was a thing and the suggest switching to `template_file`.  https://github.com/hashicorp/terraform/issues/30055

## Expected Behavior
Be able to use this module on x86 or arm64 darwin machines.  

## Steps to Reproduce
1. `terraform init` on M1 mac.  
2. See error

**Comment by beahues** [comment]
So I believe that's being pulled in through https://github.com/cloudposse/terraform-aws-datadog-lambda-forwarder/blob/373367a1338ac20706ef95c04a7ce173ebcc70e3/lambda-log.tf#L38 which has a neighbouring issue of https://github.com/cloudposse/terraform-external-module-artifact/issues/17 Not that that fixes anything by itself.

**Comment by nitrocode** [comment]
This should be closed by https://github.com/cloudposse/terraform-aws-datadog-lambda-forwarder/pull/51
