### ISSUE TITLE
Lambda role policy requires `kms:Decrypt`

### ISSUE THREAD

**Issue by bwmetcalf** [cloudposse/terraform-aws-datadog-lambda-forwarder#4]
## Describe the Bug
If the datadog api key is stored in ASM, the lambda role IAM policy requires `kms:Decrypt` privileges for the CMK used to encrypt the api key.

## Expected Behavior
The lamba function should be able to read the datadog api key from ASM.

## Steps to Reproduce
Add DD api key to ASM and use this module to create the forwarder lambda function.  Without adding
```
        {
            "Sid": "AllowKMS",
            "Effect": "Allow",
            "Action": "kms:Decrypt",
            "Resource": [
                "<cmk arn>"
            ]
        }
```
to the lamba role policy, the function throws the following error:
```
[ERROR] ClientError: An error occurred (AccessDeniedException) when calling the GetSecretValue operation: Access to KMS is not allowed
```

**Comment by nitrocode** [comment]
If you supply it with `var.s3_bucket_kms_arns` then it should add the permission. Did you try this ?

https://github.com/cloudposse/terraform-aws-datadog-lambda-forwarder/blob/df3934704ba7849a22f938e658dac62de7913e60/lambda-log.tf#L101-L111

**Comment by bwmetcalf** [comment]
> If you supply it with `var.s3_bucket_kms_arns` then it should add the permission. Did you try this ?
> 
> https://github.com/cloudposse/terraform-aws-datadog-lambda-forwarder/blob/df3934704ba7849a22f938e658dac62de7913e60/lambda-log.tf#L101-L111

A couple of issues.  One, my original bug report is against lambda-vpc-logs.tf which doesn't seem to support this.  Two, I'm pulling from cloudwatch logs.  This policy is specific to s3 and the kms that issued for the s3 bucket.

**Comment by nitrocode** [comment]
How about the following input

```hcl
  dd_api_key_source = {
    identifier = "arn:..."
    resource   = "kms"
  }
```

The identifier and resource are used to get the appropriate permission

https://github.com/cloudposse/terraform-aws-datadog-lambda-forwarder/blob/48353d5299202cf6a1ba8ada96887e74264ee93e/main.tf#L14-L18

Then they are fed into the lambda policy and attached to the iam role

https://github.com/cloudposse/terraform-aws-datadog-lambda-forwarder/blob/48353d5299202cf6a1ba8ada96887e74264ee93e/main.tf#L91-L98

**Comment by bwmetcalf** [comment]
> How about the following input
> 
> ```terraform
>   dd_api_key_source = {
>     identifier = "arn:..."
>     resource   = "kms"
>   }
> ```
> 
> The identifier and resource are used to get the appropriate permission
> 
> https://github.com/cloudposse/terraform-aws-datadog-lambda-forwarder/blob/48353d5299202cf6a1ba8ada96887e74264ee93e/main.tf#L14-L18
> 
> Then they are fed into the lambda policy and attached to the iam role
> 
> https://github.com/cloudposse/terraform-aws-datadog-lambda-forwarder/blob/48353d5299202cf6a1ba8ada96887e74264ee93e/main.tf#L91-L98

That gets you this part of the policy
```
        {
            "Sid": "AllowGetOrDecryptApiKey",
            "Effect": "Allow",
            "Action": "secretsmanager:GetSecretValue",
            "Resource": "arn:aws-us-gov:secretsmanager:........"
        },
```
but you still need
```
        {
            "Sid": "AllowKMS",
            "Effect": "Allow",
            "Action": "kms:Decrypt",
            "Resource": [
                "arn:aws-us-gov:kms:....."
            ]
        }
```
You still need permissions to use the kms key that was used to encrypt the secret.

**Comment by bwmetcalf** [comment]
The reason this is needed is the same as https://github.com/cloudposse/terraform-aws-vpc-flow-logs-s3-bucket/pull/33/files.  While encryption works for writing the vpc flow logs to cloudwatch, without `kms:Decrypt` an outside service cannot consume the logs.  The default kms policy enables IAM permissions to control access so whatever actions are needed must be attached to the lambda role/policy.

**Comment by nitrocode** [comment]
@bwmetcalf interesting. Perhaps we need to add a similar PR and add a `lambda_policy_source_json` input var ?

**Comment by bwmetcalf** [comment]
> @bwmetcalf interesting. Perhaps we need to add a similar PR and add a `lambda_policy_source_json` input var ?

In the case of using a secrets manager key where the secret is encrypted with a kms, the module will setup lambda policies that do not work useless without `kms:Decrypt` added to the policy.  Since the module is responsible for creating the lambda functions, it seems the module should also be responsible for defining and adding the kms policy.   But I'm open to the best approach.
